services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=study-group-website-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5435:5432"
volumes:
  postgres:
