query PublicationRelated($id: ID, $terms: [PublicationWhereInput!]) {
  publications(
    where: {
      status: { equals: published }
      id: { not: { equals: $id } }
      OR: $terms
    }
  ) {
    id
    slug
    title
    resume
    date
    link
    researchers {
      id
      name
    }
  }
}
